spring:
  profiles:
    active: dev
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: false
        web-admin-password: 123456