spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./h2db/sampledb2
    username: sa
    password:
    schema: classpath:init.sql
server:
  port: 8082

from:
  value: from_3307_demo2